version: "3.9"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  mock-server:
    build: .
    ports:
    - "3000:3000"
    environment:
      ISSUER: http://keycloak:8080/auth/realms/master
